### PR TITLE
WIP: Persistence refactor & improvements

### PR DESCRIPTION
**Pull request by NeumimTo**
The main goal is  to refactor the project so it will be possible for other devs to create its own dao, forcing everyone to use  bongodb is just bad, while at it ill also update to api 7 and some other improvements such as got rid of storing player instances in some caches which usually causes memoryleaks, and some major peformace improvements such as db transaction in async thread, fixed up entity move event and so on.

### CODE REVIEW

**Comment by Eufranio** [comment]
Hi! Thanks for your interest in helping this plugin, but I have some questions before merging this.
1. Why a new service? Any benefits?
2. Can you backport your changes to API5 as well? I dont really like to support only the newest version while we still have lots of servers running 1.10.2.

**Comment by NeumimTo** [comment]
I dont see any reason why this should be backported to outdated apiv5. This brings nothing new, servers which already using this plugin wont even notice that a support for a new storage type was added. 
I wont port it.

**Comment by Eufranio** [comment]
Right. Have you tested this?

**Comment by NeumimTo** [comment]
Its not finished yet thats why it is wip.

**Comment by Eufranio** [comment]
I rewrote a lot of stuff and will add a better db support soon. If you still want to PR this, update your repo/PR.

**Pull request closed without merging**
